---
task: all
docker_ce_url: "https://download.docker.com/linux/centos/docker-ce.repo"
awx_web_tag: "9.0.1"
awx_task_tag: "9.0.1"
dependencies:
  pkg:
    - python-pip
    - docker-ce
  pip:
    - docker-compose
